# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\AdminLogin.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.widget.setStyleSheet("QWidget#widget{background-color:rgb(44, 47, 51)}")
        self.widget.setObjectName("widget")
        self.loginCard = QtWidgets.QFrame(parent=self.widget)
        self.loginCard.setGeometry(QtCore.QRect(210, 49, 400, 361))
        self.loginCard.setStyleSheet("QFrame#loginCard {\n"
"    background-color: #23272A;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.loginCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginCard.setObjectName("loginCard")
        self.titleLabel = QtWidgets.QLabel(parent=self.loginCard)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 400, 50))
        self.titleLabel.setStyleSheet("font: 900 16pt \"Segoe UI\"; color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.label = QtWidgets.QLabel(parent=self.loginCard)
        self.label.setGeometry(QtCore.QRect(0, 110, 401, 31))
        self.label.setStyleSheet("font: 700 10pt \"Segoe UI\"; color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.loginCard)
        self.label_2.setGeometry(QtCore.QRect(0, 200, 400, 31))
        self.label_2.setStyleSheet("font: 700 10pt \"Segoe UI\"; color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.loginCard)
        self.usernameLineEdit.setGeometry(QtCore.QRect(0, 140, 400, 60))
        self.usernameLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #1E1F22;\n"
"    border: none;\n"
"    color: white;\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5865F2;\n"
"}\n"
"")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.loginCard)
        self.passwordLineEdit.setGeometry(QtCore.QRect(0, 240, 400, 60))
        self.passwordLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #1E1F22;\n"
"    border: none;\n"
"    color: white;\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5865F2;\n"
"}\n"
"")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginButton = QtWidgets.QPushButton(parent=self.loginCard)
        self.loginButton.setGeometry(QtCore.QRect(0, 300, 401, 61))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    font: 700 16pt \"Segoe UI\";\n"
"    color: white;\n"
"    background-color: #5865F2;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4752C4;\n"
"}\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.titleLabel_2 = QtWidgets.QLabel(parent=self.loginCard)
        self.titleLabel_2.setGeometry(QtCore.QRect(0, 50, 400, 50))
        self.titleLabel_2.setStyleSheet("font: 900 16pt \"Segoe UI\"; color: white;")
        self.titleLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel_2.setObjectName("titleLabel_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(670, 20, 101, 24))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    color: white;\n"
"    background-color: #5865F2;\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4752C4;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Abood\\Desktop\\ui\\icons/user-32.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLabel.setText(_translate("Dialog", "Conference Hall Reservation"))
        self.label.setText(_translate("Dialog", "   USERNAME"))
        self.label_2.setText(_translate("Dialog", "   PASSWORD"))
        self.usernameLineEdit.setPlaceholderText(_translate("Dialog", "Enter your username"))
        self.passwordLineEdit.setPlaceholderText(_translate("Dialog", "Enter your password"))
        self.loginButton.setText(_translate("Dialog", "LOGIN"))
        self.titleLabel_2.setText(_translate("Dialog", "ADMIN LOGIN"))
        self.pushButton.setText(_translate("Dialog", "USER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
