# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\ErrorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorDialog(object):
    def setupUi(self, ErrorDialog):
        ErrorDialog.setObjectName("ErrorDialog")
        ErrorDialog.resize(400, 250)
        ErrorDialog.setStyleSheet("background-color: #23272A;")
        self.widget = QtWidgets.QWidget(parent=ErrorDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.widget.setObjectName("widget")
        self.errorIconLabel = QtWidgets.QLabel(parent=self.widget)
        self.errorIconLabel.setGeometry(QtCore.QRect(150, 20, 100, 100))
        self.errorIconLabel.setStyleSheet("font: 72 48pt \"Segoe UI\"; color: #ED4245;")
        self.errorIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorIconLabel.setObjectName("errorIconLabel")
        self.errorMessageLabel = QtWidgets.QLabel(parent=self.widget)
        self.errorMessageLabel.setGeometry(QtCore.QRect(20, 130, 360, 40))
        self.errorMessageLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.errorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.okButton = QtWidgets.QPushButton(parent=self.widget)
        self.okButton.setGeometry(QtCore.QRect(150, 180, 100, 40))
        self.okButton.setStyleSheet("\n"
"      QPushButton {\n"
"        font: 700 12pt \"Segoe UI\";\n"
"        color: white;\n"
"        background-color: #5865F2;\n"
"        border-radius: 12px;\n"
"      }\n"
"      QPushButton:hover {\n"
"        background-color: #4752C4;\n"
"      }\n"
"     ")
        self.okButton.setObjectName("okButton")

        self.retranslateUi(ErrorDialog)
        QtCore.QMetaObject.connectSlotsByName(ErrorDialog)

    def retranslateUi(self, ErrorDialog):
        _translate = QtCore.QCoreApplication.translate
        ErrorDialog.setWindowTitle(_translate("ErrorDialog", "Error"))
        self.errorIconLabel.setText(_translate("ErrorDialog", "!"))
        self.errorMessageLabel.setText(_translate("ErrorDialog", "Invalid username or password. Please try again."))
        self.okButton.setText(_translate("ErrorDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrorDialog = QtWidgets.QDialog()
    ui = Ui_ErrorDialog()
    ui.setupUi(ErrorDialog)
    ErrorDialog.show()
    sys.exit(app.exec())
