# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\MainPage.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.widget.setStyleSheet("QWidget#widget{background-color:rgb(44, 47, 51)}")
        self.widget.setObjectName("widget")
        self.loginCard = QtWidgets.QFrame(parent=self.widget)
        self.loginCard.setGeometry(QtCore.QRect(210, 140, 400, 231))
        self.loginCard.setStyleSheet("QFrame#loginCard {\n"
"    background-color: #23272A;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.loginCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginCard.setObjectName("loginCard")
        self.cancelReservationButton = QtWidgets.QPushButton(parent=self.loginCard)
        self.cancelReservationButton.setGeometry(QtCore.QRect(10, 20, 381, 50))
        self.cancelReservationButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.cancelReservationButton.setObjectName("cancelReservationButton")
        self.cancelReservationButton_2 = QtWidgets.QPushButton(parent=self.loginCard)
        self.cancelReservationButton_2.setGeometry(QtCore.QRect(10, 160, 381, 50))
        self.cancelReservationButton_2.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: rgb(255, 0, 0);\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: rgb(199, 0, 0);\n"
"     }\n"
"    ")
        self.cancelReservationButton_2.setObjectName("cancelReservationButton_2")
        self.cancelReservationButton_3 = QtWidgets.QPushButton(parent=self.loginCard)
        self.cancelReservationButton_3.setGeometry(QtCore.QRect(10, 90, 381, 50))
        self.cancelReservationButton_3.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.cancelReservationButton_3.setObjectName("cancelReservationButton_3")
        self.titleLabel = QtWidgets.QLabel(parent=self.widget)
        self.titleLabel.setGeometry(QtCore.QRect(210, 40, 400, 50))
        self.titleLabel.setStyleSheet("font: 900 16pt \"Segoe UI\"; color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelReservationButton.setText(_translate("Dialog", "Make Reservation"))
        self.cancelReservationButton_2.setText(_translate("Dialog", "Log Out"))
        self.cancelReservationButton_3.setText(_translate("Dialog", "View Reservation"))
        self.titleLabel.setText(_translate("Dialog", "Welcome"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())