# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\MakeReservation.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReservationView(object):
    def setupUi(self, ReservationView):
        ReservationView.setObjectName("ReservationView")
        ReservationView.resize(860, 561)
        ReservationView.setStyleSheet("background-color: #23272A;")
        self.titleLabel = QtWidgets.QLabel(parent=ReservationView)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 820, 40))
        self.titleLabel.setStyleSheet("font: 900 18pt \"Segoe UI\"; color: white;")
        self.titleLabel.setObjectName("titleLabel")
        self.hallLabel = QtWidgets.QLabel(parent=ReservationView)
        self.hallLabel.setGeometry(QtCore.QRect(20, 80, 200, 25))
        self.hallLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.hallLabel.setObjectName("hallLabel")
        self.hallComboBox = QtWidgets.QComboBox(parent=ReservationView)
        self.hallComboBox.setGeometry(QtCore.QRect(20, 110, 300, 35))
        self.hallComboBox.setStyleSheet("\n"
"     QComboBox {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QComboBox:hover {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.hallComboBox.setObjectName("hallComboBox")
        self.dateLabel = QtWidgets.QLabel(parent=ReservationView)
        self.dateLabel.setGeometry(QtCore.QRect(20, 200, 200, 25))
        self.dateLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.dateLabel.setObjectName("dateLabel")
        self.dateEdit = QtWidgets.QDateEdit(parent=ReservationView)
        self.dateEdit.setGeometry(QtCore.QRect(20, 230, 300, 35))
        self.dateEdit.setStyleSheet("\n"
"     QDateEdit {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QDateEdit:hover {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.durationLabel = QtWidgets.QLabel(parent=ReservationView)
        self.durationLabel.setGeometry(QtCore.QRect(20, 280, 200, 25))
        self.durationLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.durationLabel.setObjectName("durationLabel")
        self.durationSpinBox = QtWidgets.QSpinBox(parent=ReservationView)
        self.durationSpinBox.setGeometry(QtCore.QRect(20, 310, 120, 35))
        self.durationSpinBox.setStyleSheet("\n"
"     QSpinBox {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QSpinBox:hover {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.durationSpinBox.setMinimum(1)
        self.durationSpinBox.setMaximum(12)
        self.durationSpinBox.setObjectName("durationSpinBox")
        self.slotsLabel = QtWidgets.QLabel(parent=ReservationView)
        self.slotsLabel.setGeometry(QtCore.QRect(350, 80, 450, 25))
        self.slotsLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.slotsLabel.setObjectName("slotsLabel")
        self.slotsListWidget = QtWidgets.QListWidget(parent=ReservationView)
        self.slotsListWidget.setGeometry(QtCore.QRect(350, 110, 450, 250))
        self.slotsListWidget.setStyleSheet("\n"
"     QListWidget {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 10px;\n"
"     }\n"
"    ")
        self.slotsListWidget.setObjectName("slotsListWidget")
        self.reserveButton = QtWidgets.QPushButton(parent=ReservationView)
        self.reserveButton.setGeometry(QtCore.QRect(20, 360, 300, 60))
        self.reserveButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 16pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 15px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.reserveButton.setObjectName("reserveButton")
        self.label = QtWidgets.QLabel(parent=ReservationView)
        self.label.setGeometry(QtCore.QRect(20, 160, 291, 16))
        self.label.setStyleSheet("font: 700 12pt \"Segoe UI\";\n"
"color: white;\n"
"color: rgb(0, 202, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(ReservationView)
        QtCore.QMetaObject.connectSlotsByName(ReservationView)

    def retranslateUi(self, ReservationView):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("ReservationView", "Make a New Reservation"))
        self.hallLabel.setText(_translate("ReservationView", "Select Hall"))
        self.dateLabel.setText(_translate("ReservationView", "Select Date"))
        self.durationLabel.setText(_translate("ReservationView", "Duration (hours)"))
        self.slotsLabel.setText(_translate("ReservationView", "Available Time Slots"))
        self.reserveButton.setText(_translate("ReservationView", "Reserve And Pay"))
        self.label.setText(_translate("ReservationView", "Price: $0.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReservationView = QtWidgets.QWidget()
    ui = Ui_ReservationView()
    ui.setupUi(ReservationView)
    ReservationView.show()
    sys.exit(app.exec())
