# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\ManageReservations.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MyReservationsView(object):
    def setupUi(self, MyReservationsView):
        MyReservationsView.setObjectName("MyReservationsView")
        MyReservationsView.resize(860, 560)
        MyReservationsView.setStyleSheet("background-color: #23272A;")
        self.titleLabel = QtWidgets.QLabel(parent=MyReservationsView)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 820, 40))
        self.titleLabel.setStyleSheet("font: 900 18pt \"Segoe UI\"; color: white;")
        self.titleLabel.setObjectName("titleLabel")
        self.reservationsTable = QtWidgets.QTableWidget(parent=MyReservationsView)
        self.reservationsTable.setGeometry(QtCore.QRect(20, 70, 820, 400))
        self.reservationsTable.setStyleSheet("\n"
"     QTableWidget {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       gridline-color: #5865F2;\n"
"       border-radius: 10px;\n"
"     }\n"
"     QHeaderView::section {\n"
"       background-color: #5865F2;\n"
"       color: white;\n"
"       font-weight: bold;\n"
"       border: none;\n"
"     }\n"
"    ")
        self.reservationsTable.setRowCount(0)
        self.reservationsTable.setColumnCount(5)
        self.reservationsTable.setObjectName("reservationsTable")
        item = QtWidgets.QTableWidgetItem()
        self.reservationsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reservationsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.reservationsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.reservationsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.reservationsTable.setHorizontalHeaderItem(4, item)
        self.cancelReservationButton = QtWidgets.QPushButton(parent=MyReservationsView)
        self.cancelReservationButton.setGeometry(QtCore.QRect(20, 480, 120, 50))
        self.cancelReservationButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.cancelReservationButton.setObjectName("cancelReservationButton")
        self.rescheduleReservationButton = QtWidgets.QPushButton(parent=MyReservationsView)
        self.rescheduleReservationButton.setGeometry(QtCore.QRect(160, 480, 120, 50))
        self.rescheduleReservationButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.rescheduleReservationButton.setObjectName("rescheduleReservationButton")

        self.retranslateUi(MyReservationsView)
        QtCore.QMetaObject.connectSlotsByName(MyReservationsView)

    def retranslateUi(self, MyReservationsView):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("MyReservationsView", "All Reservations"))
        item = self.reservationsTable.horizontalHeaderItem(0)
        item.setText(_translate("MyReservationsView", "Hall"))
        item = self.reservationsTable.horizontalHeaderItem(1)
        item.setText(_translate("MyReservationsView", "Date"))
        item = self.reservationsTable.horizontalHeaderItem(2)
        item.setText(_translate("MyReservationsView", "Duration"))
        item = self.reservationsTable.horizontalHeaderItem(3)
        item.setText(_translate("MyReservationsView", "Status"))
        item = self.reservationsTable.horizontalHeaderItem(4)
        item.setText(_translate("MyReservationsView", "Actions"))
        self.cancelReservationButton.setText(_translate("MyReservationsView", "Cancel"))
        self.rescheduleReservationButton.setText(_translate("MyReservationsView", "Reschedule"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyReservationsView = QtWidgets.QWidget()
    ui = Ui_MyReservationsView()
    ui.setupUi(MyReservationsView)
    MyReservationsView.show()
    sys.exit(app.exec())
