# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\ManageHall.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HallView(object):
    def setupUi(self, HallView):
        HallView.setObjectName("HallView")
        HallView.resize(860, 560)
        HallView.setStyleSheet("background-color: #23272A;")
        self.titleLabel = QtWidgets.QLabel(parent=HallView)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 820, 40))
        self.titleLabel.setStyleSheet("font: 900 18pt \"Segoe UI\"; color: white;")
        self.titleLabel.setObjectName("titleLabel")
        self.hallTable = QtWidgets.QTableWidget(parent=HallView)
        self.hallTable.setGeometry(QtCore.QRect(20, 70, 820, 400))
        self.hallTable.setStyleSheet("\n"
"     QTableWidget {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       gridline-color: #5865F2;\n"
"       border-radius: 10px;\n"
"     }\n"
"     QHeaderView::section {\n"
"       background-color: #5865F2;\n"
"       color: white;\n"
"       font-weight: bold;\n"
"       border: none;\n"
"     }\n"
"    ")
        self.hallTable.setColumnCount(4)
        self.hallTable.setRowCount(0)
        self.hallTable.setObjectName("hallTable")
        item = QtWidgets.QTableWidgetItem()
        self.hallTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hallTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hallTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hallTable.setHorizontalHeaderItem(3, item)
        self.addHallButton = QtWidgets.QPushButton(parent=HallView)
        self.addHallButton.setGeometry(QtCore.QRect(20, 480, 120, 50))
        self.addHallButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.addHallButton.setObjectName("addHallButton")
        self.editHallButton = QtWidgets.QPushButton(parent=HallView)
        self.editHallButton.setGeometry(QtCore.QRect(160, 480, 120, 50))
        self.editHallButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.editHallButton.setObjectName("editHallButton")
        self.deleteHallButton = QtWidgets.QPushButton(parent=HallView)
        self.deleteHallButton.setGeometry(QtCore.QRect(300, 480, 120, 50))
        self.deleteHallButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 12pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #5865F2;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #4752C4;\n"
"     }\n"
"    ")
        self.deleteHallButton.setObjectName("deleteHallButton")

        self.retranslateUi(HallView)
        QtCore.QMetaObject.connectSlotsByName(HallView)

    def retranslateUi(self, HallView):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("HallView", "Manage Halls"))
        item = self.hallTable.horizontalHeaderItem(0)
        item.setText(_translate("HallView", "Hall Name"))
        item = self.hallTable.horizontalHeaderItem(1)
        item.setText(_translate("HallView", "Location"))
        item = self.hallTable.horizontalHeaderItem(2)
        item.setText(_translate("HallView", "Capacity"))
        item = self.hallTable.horizontalHeaderItem(3)
        item.setText(_translate("HallView", "Actions"))
        self.addHallButton.setText(_translate("HallView", "Add Hall"))
        self.editHallButton.setText(_translate("HallView", "Edit Hall"))
        self.deleteHallButton.setText(_translate("HallView", "Delete Hall"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HallView = QtWidgets.QWidget()
    ui = Ui_HallView()
    ui.setupUi(HallView)
    HallView.show()
    sys.exit(app.exec())
