# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\PaymentTransactions.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaymentTransactions(object):
    def setupUi(self, PaymentTransactions):
        PaymentTransactions.setObjectName("PaymentTransactions")
        PaymentTransactions.resize(860, 560)
        PaymentTransactions.setStyleSheet("background-color: #23272A;")
        self.titleLabel = QtWidgets.QLabel(parent=PaymentTransactions)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 820, 40))
        self.titleLabel.setStyleSheet("font: 900 18pt \"Segoe UI\"; color: white;")
        self.titleLabel.setObjectName("titleLabel")
        self.searchLineEdit = QtWidgets.QLineEdit(parent=PaymentTransactions)
        self.searchLineEdit.setGeometry(QtCore.QRect(20, 70, 300, 35))
        self.searchLineEdit.setStyleSheet(
            """
             QLineEdit {
               background-color: #1E1F22;
               color: white;
               border-radius: 8px;
               padding-left: 10px;
             }
             QLineEdit:focus {
               border: 1px solid #5865F2;
             }
            """
        )
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.transactionsTable = QtWidgets.QTableWidget(parent=PaymentTransactions)
        self.transactionsTable.setGeometry(QtCore.QRect(20, 120, 820, 350))
        self.transactionsTable.setStyleSheet(
            """
             QTableWidget {
               background-color: #1E1F22;
               color: white;
               gridline-color: #5865F2;
               border-radius: 10px;
             }
             QHeaderView::section {
               background-color: #5865F2;
               color: white;
               font-weight: bold;
               border: none;
             }
            """
        )
        self.transactionsTable.setColumnCount(6)
        self.transactionsTable.setRowCount(0)
        self.transactionsTable.setObjectName("transactionsTable")
        item = QtWidgets.QTableWidgetItem()
        self.transactionsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionsTable.setHorizontalHeaderItem(5, item)
        self.filterComboBox = QtWidgets.QComboBox(parent=PaymentTransactions)
        self.filterComboBox.setGeometry(QtCore.QRect(340, 70, 150, 35))
        self.filterComboBox.setStyleSheet(
            """
             QComboBox {
               background-color: #1E1F22;
               color: white;
               border-radius: 8px;
               padding-left: 10px;
             }
             QComboBox:hover {
               border: 1px solid #5865F2;
             }
            """
        )
        self.filterComboBox.setObjectName("filterComboBox")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.exportButton = QtWidgets.QPushButton(parent=PaymentTransactions)
        self.exportButton.setGeometry(QtCore.QRect(720, 70, 120, 35))
        self.exportButton.setStyleSheet(
            """
             QPushButton {
               font: 700 10pt "Segoe UI";
               color: white;
               background-color: #5865F2;
               border-radius: 8px;
             }
             QPushButton:hover {
               background-color: #4752C4;
             }
            """
        )
        self.exportButton.setObjectName("exportButton")
        self.statsFrame = QtWidgets.QFrame(parent=PaymentTransactions)
        self.statsFrame.setGeometry(QtCore.QRect(20, 480, 820, 60))
        self.statsFrame.setStyleSheet(
            """
             QFrame {
               background-color: #1E1F22;
               border-radius: 10px;
             }
            """
        )
        self.statsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.statsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.statsFrame.setObjectName("statsFrame")
        self.totalLabel = QtWidgets.QLabel(parent=self.statsFrame)
        self.totalLabel.setGeometry(QtCore.QRect(20, 15, 200, 30))
        self.totalLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.totalLabel.setObjectName("totalLabel")
        self.revenueLabel = QtWidgets.QLabel(parent=self.statsFrame)
        self.revenueLabel.setGeometry(QtCore.QRect(300, 15, 200, 30))
        self.revenueLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: #57F287;")
        self.revenueLabel.setObjectName("revenueLabel")

        self.retranslateUi(PaymentTransactions)
        QtCore.QMetaObject.connectSlotsByName(PaymentTransactions)

    def retranslateUi(self, PaymentTransactions):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("PaymentTransactions", "Payment Transactions"))
        self.searchLineEdit.setPlaceholderText(_translate("PaymentTransactions", "Search transactions..."))
        item = self.transactionsTable.horizontalHeaderItem(0)
        item.setText(_translate("PaymentTransactions", "Transaction ID"))
        item = self.transactionsTable.horizontalHeaderItem(1)
        item.setText(_translate("PaymentTransactions", "User"))
        item = self.transactionsTable.horizontalHeaderItem(2)
        item.setText(_translate("PaymentTransactions", "Reservation"))
        item = self.transactionsTable.horizontalHeaderItem(3)
        item.setText(_translate("PaymentTransactions", "Amount"))
        item = self.transactionsTable.horizontalHeaderItem(4)
        item.setText(_translate("PaymentTransactions", "Date"))
        item = self.transactionsTable.horizontalHeaderItem(5)
        item.setText(_translate("PaymentTransactions", "Status"))
        self.filterComboBox.setItemText(0, _translate("PaymentTransactions", "All Transactions"))
        self.filterComboBox.setItemText(1, _translate("PaymentTransactions", "Today"))
        self.filterComboBox.setItemText(2, _translate("PaymentTransactions", "This Week"))
        self.filterComboBox.setItemText(3, _translate("PaymentTransactions", "This Month"))
        self.exportButton.setText(_translate("PaymentTransactions", "Export to CSV"))
        self.totalLabel.setText(_translate("PaymentTransactions", "Total Transactions: 125"))
        self.revenueLabel.setText(_translate("PaymentTransactions", "Total Revenue: $12,500"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentTransactions = QtWidgets.QWidget()
    ui = Ui_PaymentTransactions()
    ui.setupUi(PaymentTransactions)
    PaymentTransactions.show()
    sys.exit(app.exec())
