# Form implementation generated from reading ui file 'C:\Users\Abood\Desktop\ui\PaymentPage.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaymentPage(object):
    def setupUi(self, PaymentPage):
        PaymentPage.setObjectName("PaymentPage")
        PaymentPage.resize(860, 560)
        PaymentPage.setStyleSheet("background-color: #23272A;")
        self.titleLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 820, 40))
        self.titleLabel.setStyleSheet("font: 900 18pt \"Segoe UI\"; color: white;")
        self.titleLabel.setObjectName("titleLabel")
        self.reservationInfoLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.reservationInfoLabel.setGeometry(QtCore.QRect(20, 70, 820, 25))
        self.reservationInfoLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.reservationInfoLabel.setObjectName("reservationInfoLabel")
        self.amountLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.amountLabel.setGeometry(QtCore.QRect(20, 110, 200, 25))
        self.amountLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.amountLabel.setObjectName("amountLabel")
        self.amountValueLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.amountValueLabel.setGeometry(QtCore.QRect(230, 110, 200, 25))
        self.amountValueLabel.setStyleSheet("font: 700 14pt \"Segoe UI\"; color: #57F287;")
        self.amountValueLabel.setObjectName("amountValueLabel")
        self.paymentMethodLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.paymentMethodLabel.setGeometry(QtCore.QRect(20, 150, 200, 25))
        self.paymentMethodLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.paymentMethodLabel.setObjectName("paymentMethodLabel")
        self.paymentMethodComboBox = QtWidgets.QComboBox(parent=PaymentPage)
        self.paymentMethodComboBox.setGeometry(QtCore.QRect(20, 180, 300, 35))
        self.paymentMethodComboBox.setStyleSheet("\n"
"     QComboBox {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QComboBox:hover {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.paymentMethodComboBox.setObjectName("paymentMethodComboBox")
        self.paymentMethodComboBox.addItem("")
        self.paymentMethodComboBox.addItem("")
        self.paymentMethodComboBox.addItem("")
        self.paymentMethodComboBox.addItem("")
        self.cardNumberLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.cardNumberLabel.setGeometry(QtCore.QRect(20, 230, 200, 25))
        self.cardNumberLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.cardNumberLabel.setObjectName("cardNumberLabel")
        self.cardNumberLineEdit = QtWidgets.QLineEdit(parent=PaymentPage)
        self.cardNumberLineEdit.setGeometry(QtCore.QRect(20, 260, 300, 35))
        self.cardNumberLineEdit.setStyleSheet("\n"
"     QLineEdit {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QLineEdit:focus {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.cardNumberLineEdit.setObjectName("cardNumberLineEdit")
        self.expiryLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.expiryLabel.setGeometry(QtCore.QRect(20, 310, 200, 25))
        self.expiryLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.expiryLabel.setObjectName("expiryLabel")
        self.expiryLineEdit = QtWidgets.QLineEdit(parent=PaymentPage)
        self.expiryLineEdit.setGeometry(QtCore.QRect(20, 340, 140, 35))
        self.expiryLineEdit.setStyleSheet("\n"
"     QLineEdit {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QLineEdit:focus {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.expiryLineEdit.setObjectName("expiryLineEdit")
        self.cvvLabel = QtWidgets.QLabel(parent=PaymentPage)
        self.cvvLabel.setGeometry(QtCore.QRect(180, 310, 200, 25))
        self.cvvLabel.setStyleSheet("font: 700 12pt \"Segoe UI\"; color: white;")
        self.cvvLabel.setObjectName("cvvLabel")
        self.cvvLineEdit = QtWidgets.QLineEdit(parent=PaymentPage)
        self.cvvLineEdit.setGeometry(QtCore.QRect(180, 340, 140, 35))
        self.cvvLineEdit.setStyleSheet("\n"
"     QLineEdit {\n"
"       background-color: #1E1F22;\n"
"       color: white;\n"
"       border-radius: 8px;\n"
"       padding-left: 10px;\n"
"     }\n"
"     QLineEdit:focus {\n"
"       border: 1px solid #5865F2;\n"
"     }\n"
"    ")
        self.cvvLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.cvvLineEdit.setObjectName("cvvLineEdit")
        self.payButton = QtWidgets.QPushButton(parent=PaymentPage)
        self.payButton.setGeometry(QtCore.QRect(20, 400, 300, 50))
        self.payButton.setStyleSheet("\n"
"     QPushButton {\n"
"       font: 700 14pt \"Segoe UI\";\n"
"       color: white;\n"
"       background-color: #57F287;\n"
"       border-radius: 12px;\n"
"     }\n"
"     QPushButton:hover {\n"
"       background-color: #3BA55C;\n"
"     }\n"
"    ")
        self.payButton.setObjectName("payButton")
        self.confirmationFrame = QtWidgets.QFrame(parent=PaymentPage)
        self.confirmationFrame.setGeometry(QtCore.QRect(350, 70, 480, 380))
        self.confirmationFrame.setStyleSheet("\n"
"     QFrame {\n"
"       background-color: #1E1F22;\n"
"       border-radius: 15px;\n"
"     }\n"
"    ")
        self.confirmationFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.confirmationFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.confirmationFrame.setObjectName("confirmationFrame")
        self.confirmationIconLabel = QtWidgets.QLabel(parent=self.confirmationFrame)
        self.confirmationIconLabel.setGeometry(QtCore.QRect(190, 50, 100, 100))
        self.confirmationIconLabel.setStyleSheet("font: 72 48pt \"Segoe UI\"; color: #57F287;")
        self.confirmationIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirmationIconLabel.setObjectName("confirmationIconLabel")
        self.confirmationLabel = QtWidgets.QLabel(parent=self.confirmationFrame)
        self.confirmationLabel.setGeometry(QtCore.QRect(50, 170, 380, 40))
        self.confirmationLabel.setStyleSheet("font: 700 16pt \"Segoe UI\"; color: white;")
        self.confirmationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirmationLabel.setObjectName("confirmationLabel")
        self.confirmationDetailsLabel = QtWidgets.QLabel(parent=self.confirmationFrame)
        self.confirmationDetailsLabel.setGeometry(QtCore.QRect(50, 220, 380, 60))
        self.confirmationDetailsLabel.setStyleSheet("font: 10pt \"Segoe UI\"; color: white;")
        self.confirmationDetailsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirmationDetailsLabel.setObjectName("confirmationDetailsLabel")
        self.doneButton = QtWidgets.QPushButton(parent=self.confirmationFrame)
        self.doneButton.setGeometry(QtCore.QRect(150, 300, 180, 50))
        self.doneButton.setStyleSheet("\n"
"      QPushButton {\n"
"        font: 700 12pt \"Segoe UI\";\n"
"        color: white;\n"
"        background-color: #5865F2;\n"
"        border-radius: 12px;\n"
"      }\n"
"      QPushButton:hover {\n"
"        background-color: #4752C4;\n"
"      }\n"
"     ")
        self.doneButton.setObjectName("doneButton")

        self.retranslateUi(PaymentPage)
        QtCore.QMetaObject.connectSlotsByName(PaymentPage)

    def retranslateUi(self, PaymentPage):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("PaymentPage", "Payment"))
        self.reservationInfoLabel.setText(_translate("PaymentPage", "Reservation: Hall A - Jan 1, 2023 - 2 hours"))
        self.amountLabel.setText(_translate("PaymentPage", "Amount to Pay:"))
        self.amountValueLabel.setText(_translate("PaymentPage", "$200.00"))
        self.paymentMethodLabel.setText(_translate("PaymentPage", "Payment Method:"))
        self.paymentMethodComboBox.setItemText(0, _translate("PaymentPage", "Credit Card"))
        self.paymentMethodComboBox.setItemText(1, _translate("PaymentPage", "Debit Card"))
        self.paymentMethodComboBox.setItemText(2, _translate("PaymentPage", "PayPal"))
        self.paymentMethodComboBox.setItemText(3, _translate("PaymentPage", "Bank Transfer"))
        self.cardNumberLabel.setText(_translate("PaymentPage", "Card Number"))
        self.cardNumberLineEdit.setPlaceholderText(_translate("PaymentPage", "1234 5678 9012 3456"))
        self.expiryLabel.setText(_translate("PaymentPage", "Expiry Date"))
        self.expiryLineEdit.setPlaceholderText(_translate("PaymentPage", "MM/YY"))
        self.cvvLabel.setText(_translate("PaymentPage", "CVV"))
        self.cvvLineEdit.setPlaceholderText(_translate("PaymentPage", "123"))
        self.payButton.setText(_translate("PaymentPage", "Pay Now"))
        self.confirmationIconLabel.setText(_translate("PaymentPage", "✓"))
        self.confirmationLabel.setText(_translate("PaymentPage", "Payment Successful!"))
        self.confirmationDetailsLabel.setText(_translate("PaymentPage", "Transaction ID: CHR-123456789\n"
"Amount: $200.00\n"
"Date: Jan 1, 2023"))
        self.doneButton.setText(_translate("PaymentPage", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentPage = QtWidgets.QWidget()
    ui = Ui_PaymentPage()
    ui.setupUi(PaymentPage)
    PaymentPage.show()
    sys.exit(app.exec())
